### PR TITLE
feat: Upgrade native sdk 4.5.0

### PR DESCRIPTION
**Pull request by littleGnAl**

### CODE REVIEW

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/11092791485/agora_rtc_engine_android_6.4.0_20240929125742.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11092791485/agora_rtc_engine_ios_6.4.0_20240929125721.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11092791485/agora_rtc_engine_macos_6.4.0_20240929125236.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11092791485/agora_rtc_engine_windows_6.4.0_20240929125315.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11092791485/agora_rtc_engine_web_6.4.0_20240929125001.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/11344373003/agora_rtc_engine_android_6.4.0_20241015104705.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11344373003/agora_rtc_engine_ios_6.4.0_20241015104633.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11344373003/agora_rtc_engine_macos_6.4.0_20241015104356.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11344373003/agora_rtc_engine_windows_6.4.0_20241015104402.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11344373003/agora_rtc_engine_web_6.4.0_20241015104102.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- 
- 
- https://nightly.link/littleGnAl/hoe/actions/runs/11566969917/agora_rtc_engine_macos_6.4.0_20241029035714.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11566969917/agora_rtc_engine_windows_6.4.0_20241029035559.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11566969917/agora_rtc_engine_web_6.4.0_20241029035243.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/11568649218/agora_rtc_engine_android_6.4.0_20241029065221.zip
- 
- https://nightly.link/littleGnAl/hoe/actions/runs/11568649218/agora_rtc_engine_macos_6.4.0_20241029064626.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11568649218/agora_rtc_engine_windows_6.4.0_20241029064743.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11568649218/agora_rtc_engine_web_6.4.0_20241029064413.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/11570863108/agora_rtc_engine_android_6.4.0_20241029093155.zip
- 
- https://nightly.link/littleGnAl/hoe/actions/runs/11570863108/agora_rtc_engine_macos_6.4.0_20241029092650.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11570863108/agora_rtc_engine_windows_6.4.0_20241029092621.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11570863108/agora_rtc_engine_web_6.4.0_20241029092403.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/11570863108/agora_rtc_engine_android_6.4.0_20241029093155.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11570863108/agora_rtc_engine_ios_6.4.0_20241029095857.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11570863108/agora_rtc_engine_macos_6.4.0_20241029092650.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11570863108/agora_rtc_engine_windows_6.4.0_20241029092621.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11570863108/agora_rtc_engine_web_6.4.0_20241029092403.zip

> This comment is commented by bot, do not edit it directly

**Comment by sda-rob** [comment]
Examples built:
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/11679358645/agora_rtc_engine_android_6.4.0_20241105072843.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11679358645/agora_rtc_engine_ios_6.4.0_20241105072610.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11679358645/agora_rtc_engine_macos_6.4.0_20241105072418.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11679358645/agora_rtc_engine_windows_6.4.0_20241105072425.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/11679358645/agora_rtc_engine_web_6.4.0_20241105072127.zip

> This comment is commented by bot, do not edit it directly

**Comment by sda-rob** [comment]
Examples built:
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/11679668736/agora_rtc_engine_android_6.4.0_20241105075230.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/11679668736/agora_rtc_engine_ios_6.4.0_20241105075128.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/11679668736/agora_rtc_engine_macos_6.4.0_20241105074742.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/11679668736/agora_rtc_engine_windows_6.4.0_20241105074857.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/11679668736/agora_rtc_engine_web_6.4.0_20241105074529.zip

> This comment is commented by bot, do not edit it directly

**Comment by sda-rob** [comment]
Examples built:
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/11698946968/agora_rtc_engine_android_6.4.0_20241106081951.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/11698946968/agora_rtc_engine_ios_6.4.0_20241106081651.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/11698946968/agora_rtc_engine_macos_6.4.0_20241106081353.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/11698946968/agora_rtc_engine_windows_6.4.0_20241106072505.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/11698946968/agora_rtc_engine_web_6.4.0_20241106072137.zip

> This comment is commented by bot, do not edit it directly

**Pull request closed without merging**
