### PR TITLE
feat: upgrade native sdk 4.0.0.133.2

### PR DESCRIPTION
**Pull request by littleGnAl**
Update native sdk 4.0.0.133.2 dependencies

> This pull request is trigger by bot, you can checkout this branch and update it.

### CODE REVIEW

**Comment by littleGnAl** [comment]
Examples built:
- https://github.com/littleGnAl/hoe/releases/download/agora_rtc_engine_example_6.0.0-sp.4001332_2023-04-24/agora_rtc_engine_android_6.0.0-sp.4001332_20230424034047.zip
- https://github.com/littleGnAl/hoe/releases/download/agora_rtc_engine_example_6.0.0-sp.4001332_2023-04-24/agora_rtc_engine_ios_6.0.0-sp.4001332_20230424035628.zip
- 
- https://github.com/littleGnAl/hoe/releases/download/agora_rtc_engine_example_6.0.0-sp.4001332_2023-04-24/agora_rtc_engine_windows_6.0.0-sp.4001332_20230424033931.zip

> This comment is commented by bot, do not edit it directly

**Review by peilinok — APPROVED** [review]

**Comment by littleGnAl** [comment]
Examples built:
- https://github.com/littleGnAl/hoe/releases/download/agora_rtc_engine_example_6.0.0-sp.4001332_2023-04-24/agora_rtc_engine_android_6.0.0-sp.4001332_20230424042427.zip
- https://github.com/littleGnAl/hoe/releases/download/agora_rtc_engine_example_6.0.0-sp.4001332_2023-04-24/agora_rtc_engine_ios_6.0.0-sp.4001332_20230424042931.zip
- 
- https://github.com/littleGnAl/hoe/releases/download/agora_rtc_engine_example_6.0.0-sp.4001332_2023-04-24/agora_rtc_engine_windows_6.0.0-sp.4001332_20230424041753.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- 
- https://github.com/littleGnAl/hoe/releases/download/agora_rtc_engine_example_6.0.0-sp.4001332_2023-04-24/agora_rtc_engine_ios_6.0.0-sp.4001332_20230424082439.zip
- 
- https://github.com/littleGnAl/hoe/releases/download/agora_rtc_engine_example_6.0.0-sp.4001332_2023-04-24/agora_rtc_engine_windows_6.0.0-sp.4001332_20230424081138.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- https://github.com/littleGnAl/hoe/releases/download/agora_rtc_engine_example_6.0.0-sp.4001332_2023-04-24/agora_rtc_engine_android_6.0.0-sp.4001332_20230424090417.zip
- https://github.com/littleGnAl/hoe/releases/download/agora_rtc_engine_example_6.0.0-sp.4001332_2023-04-24/agora_rtc_engine_ios_6.0.0-sp.4001332_20230424082439.zip
- 
- https://github.com/littleGnAl/hoe/releases/download/agora_rtc_engine_example_6.0.0-sp.4001332_2023-04-24/agora_rtc_engine_windows_6.0.0-sp.4001332_20230424081138.zip

> This comment is commented by bot, do not edit it directly

**Pull request merged**
