### PR TITLE
feat: Upgrade native sdk 4.3.0

### PR DESCRIPTION
**Pull request by littleGnAl**

### CODE REVIEW

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/7139449052/agora_rtc_engine_android_6.2.6_20231208091850.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7139449052/agora_rtc_engine_ios_6.2.6_20231208092243.zip
- 
- https://nightly.link/littleGnAl/hoe/actions/runs/7139449052/agora_rtc_engine_windows_6.2.6_20231208091324.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7139449052/agora_rtc_engine_web_6.2.6_20231208091004.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/7204152015/agora_rtc_engine_android_6.2.6_20231214034416.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7204152015/agora_rtc_engine_ios_6.2.6_20231214034153.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7204152015/agora_rtc_engine_macos_6.2.6_20231214033905.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7204152015/agora_rtc_engine_windows_6.2.6_20231214033818.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7204152015/agora_rtc_engine_web_6.2.6_20231214033523.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/7666447510/agora_rtc_engine_android_6.2.6_20240126095730.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7666447510/agora_rtc_engine_ios_6.2.6_20240126095823.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7666447510/agora_rtc_engine_macos_6.2.6_20240126095559.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7666447510/agora_rtc_engine_windows_6.2.6_20240126095053.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7666447510/agora_rtc_engine_web_6.2.6_20240126094849.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/7721244644/agora_rtc_engine_android_6.2.6_20240131044153.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7721244644/agora_rtc_engine_ios_6.2.6_20240131044306.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7721244644/agora_rtc_engine_macos_6.2.6_20240131043722.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7721244644/agora_rtc_engine_windows_6.2.6_20240131044458.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7721244644/agora_rtc_engine_web_6.2.6_20240131043434.zip

> This comment is commented by bot, do not edit it directly

**Review by ever3935 — APPROVED** [review]

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/7800507841/agora_rtc_engine_android_6.2.6_20240206134247.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7800507841/agora_rtc_engine_ios_6.2.6_20240206134130.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7800507841/agora_rtc_engine_macos_6.2.6_20240206133635.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7800507841/agora_rtc_engine_windows_6.2.6_20240206133550.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7800507841/agora_rtc_engine_web_6.2.6_20240206133356.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/7956084072/agora_rtc_engine_android_6.2.6_20240219074751.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7956084072/agora_rtc_engine_ios_6.2.6_20240219074432.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7956084072/agora_rtc_engine_macos_6.2.6_20240219074035.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7956084072/agora_rtc_engine_windows_6.2.6_20240219074125.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/7956084072/agora_rtc_engine_web_6.2.6_20240219073752.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/8015165679/agora_rtc_engine_android_6.2.6_20240223054451.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/8015165679/agora_rtc_engine_ios_6.2.6_20240223054738.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/8015165679/agora_rtc_engine_macos_6.2.6_20240223053935.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/8015165679/agora_rtc_engine_windows_6.2.6_20240223054212.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/8015165679/agora_rtc_engine_web_6.2.6_20240223053533.zip

> This comment is commented by bot, do not edit it directly

**Comment by littleGnAl** [comment]
Examples built:
- https://nightly.link/littleGnAl/hoe/actions/runs/8015449562/agora_rtc_engine_android_6.3.0_20240223062301.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/8015449562/agora_rtc_engine_ios_6.3.0_20240223062307.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/8015449562/agora_rtc_engine_macos_6.3.0_20240223062058.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/8015449562/agora_rtc_engine_windows_6.3.0_20240223062216.zip
- https://nightly.link/littleGnAl/hoe/actions/runs/8015449562/agora_rtc_engine_web_6.3.0_20240223061720.zip

> This comment is commented by bot, do not edit it directly

**Pull request merged**
