### PR TITLE
feat: Upgrade native sdk 4.5.0

### PR DESCRIPTION
**Pull request by guoxianzhe**

### CODE REVIEW

**Comment by sda-rob** [comment]
Examples built:
- 
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12004869734/agora_rtc_engine_ios_6.4.0_20241125070804.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12004869734/agora_rtc_engine_macos_6.4.0_20241125070805.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12004869734/agora_rtc_engine_windows_6.4.0_20241125070330.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12004869734/agora_rtc_engine_web_6.4.0_20241125070037.zip

> This comment is commented by bot, do not edit it directly

**Comment by sda-rob** [comment]
Examples built:
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12006943519/agora_rtc_engine_android_6.4.0_20241125093049.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12006943519/agora_rtc_engine_ios_6.4.0_20241125092914.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12006943519/agora_rtc_engine_macos_6.4.0_20241125092659.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12006943519/agora_rtc_engine_windows_6.4.0_20241125092641.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12006943519/agora_rtc_engine_web_6.4.0_20241125092410.zip

> This comment is commented by bot, do not edit it directly

**Comment by sda-rob** [comment]
Examples built:
- 
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12136888842/agora_rtc_engine_ios_6.4.0_20241203120809.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12136888842/agora_rtc_engine_macos_6.4.0_20241203120622.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12136888842/agora_rtc_engine_windows_6.4.0_20241203094259.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12136888842/agora_rtc_engine_web_6.4.0_20241203094001.zip

> This comment is commented by bot, do not edit it directly

**Comment by sda-rob** [comment]
Examples built:
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12153047570/agora_rtc_engine_android_6.4.0_20241204061837.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12153047570/agora_rtc_engine_ios_6.4.0_20241204061429.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12153047570/agora_rtc_engine_macos_6.4.0_20241204061258.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12153047570/agora_rtc_engine_windows_6.4.0_20241204043357.zip
- https://nightly.link/AgoraIO-Extensions/agora_flutter_sdks_build/actions/runs/12153047570/agora_rtc_engine_web_6.4.0_20241204043059.zip

> This comment is commented by bot, do not edit it directly

**Review by peilinok — APPROVED** [review]

**Pull request merged**
