### PR TITLE
Add namespace for compatibility with AGP <4.2

### PR DESCRIPTION
**Pull request by aliyazdi75**

### CODE REVIEW

**Comment by littleGnAl** [comment]
Thanks for your contribution, btw, can you provide more detail about this change?

**Comment by aliyazdi75** [comment]
Yes,
We're trying to upgrade our project to AGP and in the upgrade process, it fails due to some packages have no `namespace` inside their gradles. Almost all popular packages such as flutter's, have this property in their own gradles. For more information you can check: https://developer.android.com/studio/build/agp-upgrade-assistant

**Comment by littleGnAl** [comment]
Cool, thanks for your contribution.

**Comment by littleGnAl** [comment]
The integration test failed since the external contributors have no access to the secret variable, and this change should not affect the test cases, so it's ok to merge.

**Review by littleGnAl — APPROVED** [review]
LGTM

**Pull request merged**
