### PR TITLE
Unnecessary Imports

### PR DESCRIPTION
**Pull request by maxxfrazer**
Removed unnecessary imports, was giving an error on pub.dev

### CODE REVIEW

**Comment by littleGnAl** [comment]
It seems it cause the tests to fail if the import is removed.

**Comment by maxxfrazer** [comment]
> It seems it cause the tests to fail if the import is removed.

I see… seems pub.dev uses a newer flutter version for the tests (3.3.0). Is there a way to fix this with backwards compatibility, or is backwards compatibility needed with Flutter?

**Comment by littleGnAl** [comment]
I think you should only change the `lib/src/impl/rtc_channel_impl.dart:3:8` and `lib/src/impl/rtc_engine_impl.dart:4:8` as the pub point out.
https://pub.dev/packages/agora_rtc_engine/score

**Comment by maxxfrazer** [comment]
Only removing those two imports won’t fix the older flutter version issue it seems.
I’ll leave it to you to fix, thanks.

**Pull request closed without merging**
